# Generated by Django 4.2.2 on 2023-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perfil_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='description',
            field=models.CharField(blank=True, default='Hola! soy Wandy este es mi blog, puedes crear tu propio blog para compartir tus ideas', max_length=500),
        ),
    ]
