# Generated by Django 4.2.2 on 2023-06-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_perfil_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
