# Generated by Django 4.2.2 on 2023-06-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_perfil_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='description',
        ),
    ]
