# Generated by Django 4.2.2 on 2023-06-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='user',
        ),
    ]
