# Generated by Django 4.2.2 on 2023-06-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_blog_user_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
    ]
