# Generated by Django 4.2.2 on 2023-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_blog_parrafo_remove_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('parrafo', models.TextField(max_length=500)),
            ],
        ),
    ]
